<?php

########################################################################
# Extension Manager/Repository config file for ext: "core4_socialmediaintegration"
#
# Auto generated by Extension Builder 2012-05-04
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Form Base',
	'description' => 'Backport of the FLOW3 Form API',
	'category' => 'plugin',
	'author' => 'Bernhard Schmitt',
	'author_email' => 'b.schmitt@core4.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '4.7',
			'fluid' => '4.7',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>